src/main.rs

Currently, it crashes when no arguments are given. `AppSettings::ArgRequiredElseHelp` can prevent it.

Show help when no command line arguments are given

---

build.rs

At least this parser uses C++11 (lambda expressions) and C++14 features
(lambda `auto` parameter types). Since the default C++ standard of
compilers can vary, this patch explicitly sets C++14 mode when building
any vendored C++ files.

Fix building of e.g., vendor/tree-sitter-haskell-src/scanner.cc

---

src/tree_sitter_parser.rs

This PR adds `cjs` and `mjs` to the extensions matched for JavaScript. Node.js uses the [`cjs` and `mjs` extensions][1] to indicate different module systems.
[1]: https://nodejs.org/api/packages.html#packages_determining_module_system

Support `cjs` and `mjs` extensions for JavaScript

---

src/guess_language.rs

This makes the test correct in case the full rule of only recognizing an Emacs mode line on the second line if the first line is a "she-bang" line is ever fully implemented.

Fix "she-bang" typo

---

src/tree_sitter_parser.rs

While I was in tree_sitter_parser for #205 I noticed that a bunch of parsers were collecting a vec to a vec (`vec![("(", ")"].into_iter().collect::<Vec<(&'static str, &'static str)>>()`, so I removed the into_iter().collect(). As long as I was doing that, I also changed the `vec!["hashset"].into_iter().collect()` into `["hashset"].into()` for brevity. Thanks!

simplify creation of atom nodes & delimiter tokens

---

src/lines.rs

Signed-off-by: Xuanwo <github@xuanwo.io>
---
Hi, this PR will fix #228 
I have tested on `janet_after.janet` and `ocaml_after.ml`.
But I'm not sure about the side effects of this patch, PTAL.
> BTW, this project is awesome :rocket:

fix: Remove trailing lines before calculating max_lines

---

Cargo.lock
Cargo.toml
src/files.rs

Signed-off-by: Xuanwo <github@xuanwo.io>
Fix #278 
Introduce `tree_magic_mini` to read magic bytes so that we can guess file media type more accurately and extensible.
In this PR, I add checks for
- pdf
- all image types
- all audio types
- all video types
- all font types

feat: Improve binary content guess

---

.github/workflows/coverage.yml
.github/workflows/deploy_docs.yml
.github/workflows/release.yml
.github/workflows/test.yml
rust-toolchain.toml

Signed-off-by: Xuanwo <github@xuanwo.io>
`1.56` is specified in tests, how about using `stable` instead?

ci: Adopt rust-toolchain instead

---

Cargo.lock
Cargo.toml
sample_files/chinese_after.po
sample_files/chinese_before.po
sample_files/compare.expected
src/display/side_by_side.rs
src/display/style.rs

This corrects this
into this
It also fixes when line continuation number columns are colored when redirected to a file / pipe.
This closes #247.

use unicode-width to align CJK characters

---

build.rs
rust-toolchain.toml

closes #253 thanks to @petrochenkov's fix mentioned there.
I just switched the order of a few lines. I did not change any in the build.rs.
The rust-toolchain.toml had to be updated to support this crate which won't compile in 1.56.1 any longer.
```
Caused by:
package `os_str_bytes v6.2.0` cannot be built because it requires rustc 1.57.0 or newer, while the currently active rustc version is 1.56.1
```

updates to support building on windows

---

Cargo.lock
Cargo.toml
src/options.rs

`term_size` crate has stopped maintenance 2 years ago.
> This crate is no longer maintained. It works fine, but the maintainers don't have time and > willingness to work on it or review future PRs anymore.
>
> Consider using [terminal_size](https://github.com/eminence/terminal-size/) instead.
https://github.com/clap-rs/term_size-rs#maintenance-status
This PR replaces the dependency with [`terminal-size`](https://github.com/eminence/terminal-size/) crate which is recommended by `term_size` crate maintainer and well maintained.

Use `terminal_size` crate instead of `term_size` crate

---

build.rs

Fix https://github.com/Wilfred/difftastic/issues/342 by adding `/utf-8` flag to cl.exe.
Ref. https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170

Fix: Can't build on Windows in a locale whose default encoding is not UTF-8

---

src/options.rs

"ON" and "OFF" in uppercase are not accepted. Print help in lowercase to match accepted values.

Fix help-value for "--syntax-highlight" argument.

---

README.md

Manual pages at https://difftastic.wilfred.me.uk/ lists more than 30 languages and reports "It supports over 30 programming languages and when it works, it's fantastic.".
The chances are you forgot to update the README.md file.

20 known languages => 30

---

Cargo.toml

Right now `cargo binstall` cannot find the pre-compiled `difftastic` assets:
```
~
❯ cargo binstall difftastic
INFO resolve: Resolving package: 'difftastic'
WARN resolve: The package will be installed from source (with cargo)
Do you wish to continue? yes/[no]
? no
WARN Installation cancelled
~ took 18s
❯ cargo binstall difftastic --pkg-url="{ repo }/releases/download/{ version }/difft-{ target }.{ archive-format }"
INFO resolve: Resolving package: 'difftastic'
WARN resolve: The package will be downloaded from github.com
INFO resolve: This will install the following binaries:
INFO resolve:   - difft (difft -> /home/michel/.cargo/bin/difft-v0.38.0)
INFO resolve: And create (or update) the following symlinks:
INFO resolve:   - difft (/home/michel/.cargo/bin/difft -> difft-v0.38.0)
Do you …
```

Add `cargo binstall` metadata

---

src/options.rs

This fixes https://github.com/Wilfred/difftastic/issues/296.

Check arguments passed from Git for `/dev/null`

---

Cargo.toml

For dependencies we're pinning for Rust 1.57 compatibility, specify the range of versions allowed rather than just pinning to the maximum version allowed.
This makes it easier for Linux distribution packaging, where a different version might already be packaged.

Relax version dependencies

---

manual/src/mercurial.md

The `--missing-as-empty` option has been removed in version 0.46.

doc: update mercurial configuration example

---

manual/src/mercurial.md

Mention that command-line arguments can be added, and that `hg dft` supports all arguments `hg diff` does.
Seeing the `hg dft` incantation below, it took me a moment to realise that `hg dft` will then support comparing revisions.
Perhaps a better change would be to tweak the description of the `hg log -p` section: any two revisions can be compared like this, not just the working directory to the latest revision checked out.

doc: extend description of mercurial configuration

---

.github/workflows/release.yml

Github sends out an email on creating/publishing a release (Watch -> Custom -> releases) and that email contains whatever is at that point in the release description. As the pipeline currently creates a release without a description the email is mostly empty. As the changelog is added manually later, lets only create a draft release which can be "published" after adding the changelog. The release email then contains a proper changelog entry.

Create draft release in pipeline

---

src/files.rs

If `lhs_paths` and `rhs_paths` are `["a", "c"]` and `["a", "b", "c"]` respectively, the loop ends with `paths = ["a", "c", "b"], i = j = 2`. We still need to deduplicate "c" from the `rhs_paths`.
.into_iter() can't be used anymore since the seen set still borrows the paths.

Fix dir-diff paths merging to not add duplicated entries from remainder

---

manual/src/adding_a_parser.md

The `LANG_*` lists were removed and replaced with functions in 4d85b5c15e60e5cfc396a35b3686df4d7210a925.

manual: fix instructions for adding new parser

---

src/parse/guess_language.rs

Zope and Plone ZCML (Zope Configuration Markup Language) is XML.

ZCML is XML

---

src/display/json.rs
src/main.rs

Today, JSON output doesn't respect the `skip-unchanged` param, and outputs all files regardless. This can result in unnecessarily big outputs. 
This fixes it

Allow JSON output to respect skip-unchanged

---

manual/src/git.md

There's a feature of Git's completion scripts that allows completing function aliases[1]:
> If you use complex aliases of form '!f() { ... }; f', you can use the null
> command ':' as the first command in the function body to declare the desired
> completion style
This allows completion:
$ git dlog --pat<tab>
--patch             --patch-with-raw    --patch-with-stat   --patience
Tested on `bash`, though I believe this should also work with `zsh` and `tsch` since their respective completion scripts also make use of the `bash` one
[1] https://git.kernel.org/pub/scm/git/git.git/tree/contrib/completion/git-completion.bash?id=11c821f2f2a31e70fb5cc449f9a29401c333aad2#n26

Add tab completion for documented `dlog` alias

---

Cargo.lock

Just running `cargo update` on it's own bumped our transitive dependency on mio from 0.8.11 to 0.8.12 which fixed an actual serious [security vulnerability](https://rustsec.org/advisories/RUSTSEC-2024-0019)

(Fix RUSTSEC2024-0019 by) run cargo update

---

manual/src/git.md

Use `-c` to set config instead of environment variable, so no need for building shell command

Much shorter version of dlog alias in git documentation

---

src/diff/dijkstra.rs
src/diff/graph.rs
src/diff/stack.rs

Vertex is allocated on the arena, so it is never dropped; then it cannot contain a Vec allocated on the regular heap without leaking memory. Replace the Vec with a slice allocated on the arena, which seems to fix most of the leaks. (Some may remain; I haven't checked fully.) It should also be slightly more memory-efficient.
It's not clear that we actually need the RefCell instead of just putting Option directly into the structure, but I've let it stay.
This issue was probably introduced in a71d6118cf52.

Fix memory leak in neighbours array.

---

Cargo.lock
Cargo.toml

This includes the fix to https://github.com/rust-lang/cc-rs/issues/909 which spams warnings on ubuntu 22.04

Update the cc package to 1.1.5

---

src/line_parser.rs

This PR fixes #688, and adds a test for the case.

fix: Off-by-one when text change longer than MAX_WORDS_PER_LINE

---

demo_files/1/src/main.rs
demo_files/2/src/main.rs
manual/src/installation.md
src/main.rs
src/options.rs

Fix wording in the command-line help text as well as in some comments.

Add Scoop installation instructions for Windows

---

manual/src/git.md

This makes the config option identical to running `git config --global alias.dlog '-c diff.external=difft log -p --ext-diff'`.

[docs] Remove unnecessary double quotes in Git alias

---

.github/workflows/coverage.yml
.github/workflows/deploy_docs.yml
.github/workflows/release.yml
.github/workflows/test.yml
manual/book.toml
manual/src/tree_diffing.md
src/parse/syntax.rs
translation/zh-CN/manual-zh-CN/book.toml

This PR bumps GitHub action workflows to their latest versions, thus avoiding deprecation warnings as seen e.g. [here](https://github.com/Wilfred/difftastic/actions/runs/10715614378).
This PR also fixes a few typos on the way.

Bump GitHub action workflows to their latest versions

---

manual/src/installation.md

* Introduce OS sections
* Introduce general intro text
* Highlight differentiators (OS and package managers)
* Use consistent source code spacing
* Add Windows `winget` instruction

docs(install): Improve and extend Installation docs

---

manual/src/contributing.md

The difftastic `Cargo.toml` currently specifies Rust version 1.66 to be used.
When running `cargo install mdbook` in the repository directory or manual sub-directory, the installation fails.
With a more recent Rust toolchain active, which can reasonably be assumed outside of the repository directory, the mdbook installation works fine.
If the user does not have a more recent toolchain active outside of the directory, the note at least serves as a pointer to the issue.
---
The error in question:
```
error: failed to compile `mdbook v0.4.40`, intermediate artifacts can be found at `[…]\Temp\cargo-install[…]`
Caused by:
failed to select a version for `env_logger`.
... required by package `mdbook v0.4.40`
versions that meet the requirements `^0.11.1` are: 0.11.5, 0.11.4, 0.11.3, 0.11.2, …
```

docs(contributing): Add mdbook install note about toolchain

---

sample_files/compare_all.sh

I have cargo configured to have a global target directory (in my case, at /tmp/cargo). The output directory for cargo builds is not guarunteed to be at ./target.
This could alternatively be solved by the user with strange defaults (me) making a symlink like `ln -s /tmp/cargo ./target`, which doesn't require having `jq` installed.

compare_all.sh: get difft binary using `cargo metadata`

---

homepage/home_static/style.css
homepage/index.html

- Set a fixed width on the GitHub logo to prevent reflow while loading
- Set `pointer-events: none;` so clicking the logo still links correctly
https://github.com/user-attachments/assets/68e942d9-4a5b-4cb1-b063-954b25329787
https://github.com/user-attachments/assets/90f88fc7-3ea5-4e19-8066-5f3641e6037f

Fix GitHub logo reflow

---

.github/workflows/release.yml
.github/workflows/test.yml

I have tested [the binary](https://github.com/Master-Hash/difftastic/releases/tag/0.65.0) on my machine. All CI tests pass. 
I don't think the code need modification, and hopefully I modified all the CI script needed.

ci: build & test for aarch64-pc-windows-msvc target

---

Cargo.toml
src/main.rs

This is a minor portability fix.
jemalloc does not work on illumos, but fortunately, its use within difftastic is already conditional on the target environment not being msvc, so simply extend that conditional involved to also exclude illumos.

Do not use jemalloc on illumos
